DROP SCHEMA daltimetable;
CREATE SCHEMA IF NOT EXISTS daltimetable;
USE daltimetable;

CREATE TABLE department (
    D_CODE VARCHAR(4) UNIQUE,
    D_NAME VARCHAR(64),
    PRIMARY KEY (D_CODE)
);

CREATE TABLE terms (
    T_CODE SMALLINT(2),
    YR SMALLINT(4),
    TERM VARCHAR(6),
    PRIMARY KEY (T_CODE)
);

CREATE TABLE districts (
    DIS_CODE SMALLINT(3),
    DIS_NAME VARCHAR(12),
    PRIMARY KEY (DIS_CODE)
);

CREATE TABLE classInfo (
    C_CRN SMALLINT(5),
    T_CODE SMALLINT(2),
    C_NAME VARCHAR(64) NOT NULL,
    D_CODE VARCHAR(4) NOT NULL,
    DIS_CODE SMALLINT(3) NOT NULL,
    C_CODE VARCHAR(6) NOT NULL,
    C_DAYS VARCHAR(5) NOT NULL,
    C_TIMESTART TIME NOT NULL,
    C_TIMEEND TIME NOT NULL,
    C_CREDIT_HRS SMALLINT(2),
    C_SIZE SMALLINT(3),
    C_NUM_REGISTERED SMALLINT(3),
    C_PROF VARCHAR(64),
    PRIMARY KEY (C_CRN, T_CODE),
    FOREIGN KEY (D_CODE) REFERENCES department (D_CODE),
    FOREIGN KEY (T_CODE) REFERENCES terms (T_CODE),
    FOREIGN KEY (DIS_CODE) REFERENCES districts (DIS_CODE)
);

CREATE TABLE labInfo (
    L_CRN SMALLINT(5),
    L_DAYS VARCHAR(5),
    L_TIMESTART TIME,
    L_TIMEEND TIME,
    L_SIZE SMALLINT(3),
    L_NUM_REGISTERED SMALLINT(3),
    L_IS_TUTORIAL TINYINT(1),
    T_CODE SMALLINT(2),
    PRIMARY KEY (L_CRN, T_CODE),
    FOREIGN KEY (T_CODE) REFERENCES terms (T_CODE)
);

CREATE TABLE classLabs (
    T_CODE SMALLINT(2),
    C_CRN SMALLINT(5),
    L_CRN SMALLINT(5),
    PRIMARY KEY (T_CODE, C_CRN, L_CRN),
    FOREIGN KEY (C_CRN, T_CODE) REFERENCES classInfo (C_CRN, T_CODE),
    FOREIGN KEY (L_CRN, T_CODE) REFERENCES labInfo (L_CRN, T_CODE),
    FOREIGN KEY (T_CODE) REFERENCES terms (T_CODE)
);
